function explanation = genai_explain(floodProb, landslideProb, slopeDeg, elevationNow, rainfallNow)
%GENAI_EXPLAIN Generates human-readable risk explanation
%   Inputs:
%   floodProb       - Flood probability (%)
%   landslideProb   - Landslide probability (%)
%   slopeDeg        - Terrain slope (degrees)
%   elevationNow    - Elevation (meters)
%   rainfallNow     - Rainfall (mm)

if landslideProb >= floodProb && landslideProb >= 40
    % Landslide-dominant explanation
    explanation = sprintf([ ...
        'High landslide risk detected.\n' ...
        'Reasoning:\n' ...
        '• Terrain slope is %.1f degrees, indicating unstable hilly terrain.\n' ...
        '• Elevation of %.0f meters increases susceptibility to slope failure.\n' ...
        '• Rainfall of %.0f mm can reduce soil strength and trigger landslides.\n\n' ...
        'Advisory Actions:\n' ...
        '- Avoid hill roads and steep slopes.\n' ...
        '- Watch for ground cracks, tilting trees, or falling rocks.\n' ...
        '- Follow local authority warnings.\n'], ...
        slopeDeg, elevationNow, rainfallNow);

elseif floodProb > landslideProb && floodProb >= 40
    % Flood-dominant explanation
    explanation = sprintf([ ...
        'Flood risk is significant.\n' ...
        'Reasoning:\n' ...
        '• Rainfall of %.0f mm exceeds normal drainage capacity.\n' ...
        '• Low or moderate elevation areas may experience water accumulation.\n' ...
        '• Soil conditions may slow water infiltration.\n\n' ...
        'Advisory Actions:\n' ...
        '- Move to higher ground if rainfall continues.\n' ...
        '- Avoid crossing flooded roads or streams.\n' ...
        '- Secure valuables and follow evacuation advisories.\n'], ...
        rainfallNow);

else
    % Low-risk / No-disaster explanation
    explanation = sprintf([ ...
        'Low disaster risk at present.\n' ...
        'Reasoning:\n' ...
        '• Terrain slope (%.1f degrees) is within stable limits.\n' ...
        '• Rainfall of %.0f mm is not critical.\n' ...
        '• Elevation of %.0f meters shows no immediate hazard indicators.\n\n' ...
        'Advisory Actions:\n' ...
        '- Normal conditions.\n' ...
        '- Continue routine monitoring, especially during monsoon periods.\n'], ...
        slopeDeg, rainfallNow, elevationNow);
end

end
